apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-validation-deployment
  labels:
    app: address-validation-service
spec:
  template:
    spec:
      containers:
        - name: address-validation-service
          image: workshopapimanagementacrmadsummit24.azurecr.io/address-validation:latest