apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer-service
spec:
  template:
    spec:
      containers:
        - name: customer-service
          image: workshopapimanagementacrmadsummit24.azurecr.io/customer:latest