apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
# Deployments
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: address-validation-deployment
    path: patches/deployments/address-acr-name-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: billing-deployment
    path: patches/deployments/billing-acr-name-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: customer-deployment
    path: patches/deployments/customer-acr-name-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: delivery-deployment
    path: patches/deployments/delivery-acr-name-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: backstage-deployment
    path: patches/deployments/backstage-acr-name-patch.yaml
#Ingresses
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: address-validation-ingress
    path: patches/ingresses/address-validation-ingress-patch.yml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: backstage-ingress
    path: patches/ingresses/backstage-ingress-patch.yml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: billing-ingress
    path: patches/ingresses/billing-ingress-patch.yml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: customer-ingress
    path: patches/ingresses/customer-ingress-patch.yml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: delivery-ingress
    path: patches/ingresses/delivery-ingress-patch.yml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: pact-ingress
    path: patches/ingresses/pact-ingress-patch.yml


resources:
  - ../../base/