controller:
  updateStrategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: 1
  hostPort:
    enabled: true
  terminationGracePeriodSeconds: 0
  service:
    type: "NodePort"
  watchIngressWithoutClass: true
  nodeSelector:
    ingress-ready: "true"
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      effect: "NoSchedule"
  publishService:
    enabled: false
  extraArgs:
    publish-status-address: "localhost"
  annotations:
    linkerd.io/inject: enabled
    "config.linkerd.io/default-inbound-policy": "all-unauthenticated"
  podAnnotations:
    linkerd.io/inject: enabled
    "config.linkerd.io/default-inbound-policy": "all-unauthenticated"