prometheus:
  ingress:
    enabled: true
    ingressClassName: webapprouting.kubernetes.azure.com
    hosts:
      - prometheus.api-workshop-0.azure.cloud.openknowledge.services
      - prometheus.api-workshop-1.azure.cloud.openknowledge.services
      - prometheus.api-workshop-2.azure.cloud.openknowledge.services
      - prometheus.api-workshop-3.azure.cloud.openknowledge.services
      - prometheus.api-workshop-4.azure.cloud.openknowledge.services
      - prometheus.api-workshop-5.azure.cloud.openknowledge.services
      - prometheus.api-workshop-6.azure.cloud.openknowledge.services
      - prometheus.api-workshop-7.azure.cloud.openknowledge.services
      - prometheus.api-workshop-8.azure.cloud.openknowledge.services
      - prometheus.api-workshop-9.azure.cloud.openknowledge.services
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminUser: admin
  adminPassword: admin
  ingress:
    enabled: true
    ingressClassName: webapprouting.kubernetes.azure.com
    hosts:
      - grafana.api-workshop-0.azure.cloud.openknowledge.services
      - grafana.api-workshop-1.azure.cloud.openknowledge.services
      - grafana.api-workshop-2.azure.cloud.openknowledge.services
      - grafana.api-workshop-3.azure.cloud.openknowledge.services
      - grafana.api-workshop-4.azure.cloud.openknowledge.services
      - grafana.api-workshop-5.azure.cloud.openknowledge.services
      - grafana.api-workshop-6.azure.cloud.openknowledge.services
      - grafana.api-workshop-7.azure.cloud.openknowledge.services
      - grafana.api-workshop-8.azure.cloud.openknowledge.services
      - grafana.api-workshop-9.azure.cloud.openknowledge.services
  additionalDataSources:
    - name: loki
      type: loki
      url: http://loki-read:3100
      editable: true
    - name: Jaeger
      type: jaeger
      url: http://jaeger-query:16686
      editable: true
      jsonData:
      tracesToLogsV2:
        # Field with an internal link pointing to a logs data source in Grafana.
        # datasourceUid value must match the uid value of the logs data source.
        datasourceUid: 'loki'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        tags: [ 'job', 'instance', 'pod', 'namespace' ]
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: 'method="${__span.tags.method}"'
