apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: workshop-service-management
build:
  artifacts:
    - image: workshopapimanagementacrapidesigncamp.azurecr.io/address-validation
      context: address-validation-service
      docker:
        dockerfile: Dockerfile
    - image: workshopapimanagementacrapidesigncamp.azurecr.io/billing
      context: billing-service
      docker:
        dockerfile: Dockerfile
    - image: workshopapimanagementacrapidesigncamp.azurecr.io/customer
      context: customer-service
      docker:
        dockerfile: Dockerfile
    - image: workshopapimanagementacrapidesigncamp.azurecr.io/delivery
      context: delivery-service
      docker:
        dockerfile: Dockerfile
    - image: workshopapimanagementacrapidesigncamp.azurecr.io/backstage
      context: backstage
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
#      - name: ingress-nginx
#        repo: https://kubernetes.github.io/ingress-nginx
#        remoteChart: ingress-nginx
#        namespace: ingress-nginx
#        createNamespace: true
      - name: kube-prometheus-stack
        repo: https://prometheus-community.github.io/helm-charts
        remoteChart: kube-prometheus-stack
        namespace: observability
        createNamespace: true
        valuesFiles:
          - ./kube-prometheus-stack-values.yaml
      - name: cert-manager
        repo: https://charts.jetstack.io
        remoteChart: cert-manager
        namespace: cert-manager
        createNamespace: true
        setValues:
          installCRDs: true
      - name: jaeger-operator
        repo: https://jaegertracing.github.io/helm-charts
        remoteChart: jaeger-operator
        namespace: observability
        createNamespace: true
      - name: opentelemetry-operator
        repo: https://open-telemetry.github.io/opentelemetry-helm-charts
        remoteChart: opentelemetry-operator
        namespace: observability
        createNamespace: true
        valuesFiles:
          - ./otel-operator-values.yaml
      - name: loki
        repo: https://grafana.github.io/helm-charts
        remoteChart: loki
        namespace: observability
        createNamespace: true
        valuesFiles:
          - ./loki-values.yaml
      - name: promtail
        repo: https://grafana.github.io/helm-charts
        remoteChart: promtail
        namespace: observability
        createNamespace: true
        valuesFiles:
          - ./promtail-values.yaml
  statusCheckDeadlineSeconds: 300
  tolerateFailuresUntilDeadline: true
  kubectl: {}

manifests:
  kustomize:
    paths:
      - deployment/base

profiles:
  - name: adc-1
    activation:
      - kubeContext: workshop-cluster-apidesigncamp-1
    patches:
      - op: replace
        path: /manifests/kustomize/paths
        value:
          - deployment/api-design-camp/adc-1
  - name: adc-2
    activation:
      - kubeContext: workshop-cluster-apidesigncamp-2
    patches:
      - op: replace
        path: /manifests/kustomize/paths
        value:
         - deployment/api-design-camp/adc-2
  - name: adc-3
    activation:
      - kubeContext: workshop-cluster-apidesigncamp-3
    patches:
      - op: replace
        path: /manifests/kustomize/paths
        value:
          - deployment/api-design-camp/adc-3
  - name: adc-4
    activation:
      - kubeContext: workshop-cluster-apidesigncamp-4
    patches:
      - op: replace
        path: /manifests/kustomize/paths
        value:
          - deployment/api-design-camp/adc-4
  - name: adc-5
    activation:
      - kubeContext: workshop-cluster-apidesigncamp-5
    patches:
      - op: replace
        path: /manifests/kustomize/paths
        value:
          - deployment/api-design-camp/adc-5