apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: workshop-service-management
build:
  artifacts:
    - image: docker.host.internal:5000/address-validation
      context: address-validation-service
      docker:
        dockerfile: Dockerfile
    - image: docker.host.internal:5000/billing
      context: billing-service
      docker:
        dockerfile: Dockerfile
    - image: docker.host.internal:5000/customer
      context: customer-service
      docker:
        dockerfile: Dockerfile
    - image: docker.host.internal:5000/delivery
      context: delivery-service
      docker:
        dockerfile: Dockerfile
    - image: docker.host.internal:5000/backstage
      context: backstage
      docker:
        dockerfile: Dockerfile

deploy:
  helm:
    releases:
      - name: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx
        remoteChart: ingress-nginx
        namespace: ingress-nginx
        createNamespace: true
        valuesFiles:
          - ./ingress-nginx-values.yaml
  statusCheckDeadlineSeconds: 300
  tolerateFailuresUntilDeadline: true

  kubectl: {}

manifests:
  kustomize:
    paths:
      - deployment/base
