apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: billing-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - host: billing.ok-cluster.azure.cloud.openknowledge.services
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: billing-service
                port:
                  number: 8080
