apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-deployment
  labels:
    app: backstage
spec:
  template:
    spec:
      containers:
        - name: backstage
          image: docker.host.internal:5000/backstage:latest
