apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-deployment
  labels:
    app: delivery-service
spec:
  template:
    spec:
      containers:
        - name: delivery-service
          image: docker.host.internal:5000/delivery:latest