apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    options:
      prometheus:
        server-url: "http://prometheus-operated.observability:9090"
    metricsStorage:
      type: prometheus
  ingress:
    enabled: true
    ingressClassName: nginx # webapprouting.kubernetes.azure.com
    hosts:
      - jaeger.localhost
      - jaeger.ok-cluster.azure.cloud.openknowledge.services
      - jaeger.api-workshop-0.azure.cloud.openknowledge.services
      - jaeger.api-workshop-1.azure.cloud.openknowledge.services
      - jaeger.api-workshop-2.azure.cloud.openknowledge.services
      - jaeger.api-workshop-3.azure.cloud.openknowledge.services
      - jaeger.api-workshop-4.azure.cloud.openknowledge.services
      - jaeger.api-workshop-5.azure.cloud.openknowledge.services
      - jaeger.api-workshop-6.azure.cloud.openknowledge.services
      - jaeger.api-workshop-7.azure.cloud.openknowledge.services
      - jaeger.api-workshop-8.azure.cloud.openknowledge.services
      - jaeger.api-workshop-9.azure.cloud.openknowledge.services
