apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    options:
      prometheus:
        server-url: "http://prometheus-operated.observability:9090"
    metricsStorage:
      type: prometheus
  ingress:
    enabled: true
    ingressClassName: webapprouting.kubernetes.azure.com
    hosts:
      - jaeger.ok-cluster.azure.cloud.openknowledge.services
      - jaeger.api-workshop-management-0.azure.cloud.openknowledge.services
      - jaeger.api-workshop-management-1.azure.cloud.openknowledge.services
      - jaeger.api-workshop-management-2.azure.cloud.openknowledge.services
      - jaeger.api-workshop-management-3.azure.cloud.openknowledge.services
      - jaeger.api-workshop-management-4.azure.cloud.openknowledge.services
      - jaeger.api-workshop-management-5.azure.cloud.openknowledge.services
      - jaeger.api-workshop-management-6.azure.cloud.openknowledge.services
      - jaeger.api-workshop-management-7.azure.cloud.openknowledge.services
      - jaeger.api-workshop-management-8.azure.cloud.openknowledge.services
      - jaeger.api-workshop-management-9.azure.cloud.openknowledge.services
