apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-validation-deployment
  labels:
    app: address-validation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-validation-service
  template:
    metadata:
      labels:
        app: address-validation-service
      annotations:
        sidecar.opentelemetry.io/inject: "otel-collector"
        instrumentation.opentelemetry.io/inject-java: "true"
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: address-validation-service
          image: docker.host.internal:5000/address-validation:latest
          ports:
            - containerPort: 8080
              name: http