apiVersion: v1
kind: Service
metadata:
  name: pact
spec:
  selector:
    app: pact
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30091
      name: service

